name: "[buildpacks] CI Pipeline"
on: # rebuild any PRs and main branch changes
  pull_request_target:
    types:
      - synchronize
      - labeled
    branches:
      - main
      - bitnami:main
permissions:
  issues: write
  pull-requests: write
  statuses: write
env:
  CSP_API_URL: https://console.cloud.vmware.com
  CSP_API_TOKEN: ${{ secrets.CSP_API_TOKEN }}
  VIB_ENV_TARGET_PLATFORM: ${{ secrets.VIB_ENV_TARGET_PLATFORM }}
  VIB_PUBLIC_URL: https://cp.bromelia.vmware.com
jobs:
  vib-verify:
    runs-on: ubuntu-latest
    name: VIB Verify
    continue-on-error: false
    steps:
      - uses: actions/checkout@v3
        name: checkout-repository
        with:
          # Full history is not required anymore
          fetch-depth: 1
          # labeled events trigger the event with the latest commit in main
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - id: generate-short-sha
        name: generate-short-sha
        run: |
          echo "short-sha=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT
      - uses: vmware-labs/vmware-image-builder-action@0.4.11
        name: verify
        with:
          pipeline: .vib/buildpack/vib-verify.json
        env:
          VIB_ENV_SHA: ${{ steps.generate-short-sha.outputs.short-sha }}
