name: "[layers-dockerfile] CI Pipeline"
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
      - .vib/**
      - containerize/layers-dockerfile/**
permissions:
  issues: write
  pull-requests: write
  statuses: write
env:
  CSP_API_URL: https://console.cloud.vmware.com
  CSP_API_TOKEN: ${{ secrets.CSP_API_TOKEN }}
  VIB_ENV_TARGET_PLATFORM: ${{ secrets.VIB_ENV_TARGET_PLATFORM }}
  VIB_PUBLIC_URL: https://cp.bromelia.vmware.com
jobs:
  vib-verify:
    runs-on: ubuntu-latest
    name: VIB Verify
    continue-on-error: false
    steps:
      - uses: actions/checkout@v3
        name: checkout-repository
        with:
          # Full history is not required anymore
          fetch-depth: 1
          # labeled events trigger the event with the latest commit in main
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - id: generate-short-sha
        name: generate-short-sha
        run: |
          echo "short-sha=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

      - id: set-up-jdk-17
        name: set-up-jdk-17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: liberica
          cache: maven

      - id: prepare-jar
        name: prepare-jar
        run: |
          cd containerize/layers-dockerfile
          mvn -B clean package -DskipTests
          cd ../ && tar -czf layers-dockerfile-with-artifacts.tar.gz ./layers-dockerfile/*

      - name: upload-dockerfile-with-artifacts
        id: upload-dockerfile-with-artifacts
        uses: actions/upload-artifact@v3
        with:
          name: layers-dockerfile-with-artifacts
          path: containerize/layers-dockerfile-with-artifacts.tar.gz
          if-no-files-found: error

      - name: prepare-dockerfile-with-artifacts-url
        id: prepare-dockerfile-with-artifacts-url
        env:
          GITHUB_TOKEN: ${{ secrets.GH_DANI8ART_PAT }}
          RUN_ID: ${{ github.event.client_payload.run_id || github.event.inputs.run_id }}
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/artifacts \
            > artifacts.json

          jq -r '.' artifacts.json

          ARTIFACT_URL="$(jq -r '.artifacts[] | select(.name == "layers-dockerfile-with-artifacts") | .archive_download_url' artifacts.json)"

          echo "url=${ARTIFACT_URL}"
          echo "url=${ARTIFACT_URL}" >> $GITHUB_OUTPUT

      - uses: vmware-labs/vmware-image-builder-action@0.4.12
        name: verify
        with:
          pipeline: container-image-package/vib-verify.json
        env:
          VIB_ENV_SHA: ${{ steps.generate-short-sha.outputs.short-sha }}
          VIB_ENV_DOCKERFILE_WITH_ARTIFACTS_URL: ${{ steps.prepare-dockerfile-with-artifacts-url.outputs.url }}
          VIB_ENV_GITHUB_PAT: ${{ secrets.GH_DANI8ART_PAT }}
